config/routes.rb
Rails.application.routes.draw do


  get 'likes/create'
  get 'likes/destroy'
  get 'imgposts/new'
  root to: 'homes#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :imgposts ,only:[:new, :index, :create, :destroy]
  resources :users, except: [:index]
  resources :posts
  
  get '*path', controller: 'application', action: 'render_404'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imgpost.rb
class Imgpost < ApplicationRecord
  mount_uploader :img, ImgUploader

  belongs_to :user

  validates :name, presence: true
  validates :img, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :content, presence: true, length: {maximum: 50}

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :posts
  has_many :imgposts

  validates :name, presence: true, length: { maximum: 10}
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 8}





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :current_user?
  before_action :login_required
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404

  def render_404
    flash.now[:alert]="エラーページです。"
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  private

  def current_user
    @current_user ||=User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    unless current_user
      flash[:alert]="ログインしてください。"
      redirect_to login_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  skip_before_action :login_required

  def index
  end
end

app/controllers/imgposts_controller.rb
class ImgpostsController < ApplicationController

  def index
    @imgposts=Imgpost.all.order(created_at: :desc).page(params[:page]).per(9)
  end

  def new
    @imgpost=Imgpost.new
  end

  def create
    @imgpost=current_user.imgposts.new(imgpost_params)

    if @imgpost.save
      redirect_to imgposts_path
    else
      flash.now[:alert]="画像の投稿に失敗しました。"
      render :new
    end
  end

  def destroy
    @imgpost=current_user.imgposts.find(params[:id])

    @imgpost.destroy
    flash[:notice]="画像名:#{@imgpost.name}を削除しました。"
    redirect_to imgposts_path
  end

  private

  def imgpost_params
    params.require(:imgpost).permit(:name, :img)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.iine(current_user)
  end

  def destroy
    @post = Like.find(params[:id]).post
    @post.uniine(current_user)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only:[:edit, :show, :update, :destroy]


  def index
    @posts=Post.all.order(created_at: :desc).page(params[:page]).per(30)
  end

  def new
    @post=Post.new
  end

  def create
    @post=current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      flash.now[:alert]="1文字以上50文字以内でテキストを入力してください。"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      flash.now[:alert]="1文字以上50文字以内でテキストを編集してください。"
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice]="投稿番号#{@post.id}を削除しました。"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post=current_user.posts.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :login_required
  def new
  end

  def create
    user=User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id]=user.id
      flash[:notice]="#{user.name}さん、ログインに成功しました。"
      redirect_to posts_path
    else
      flash.now[:alert]="ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    reset_session
    flash[:notice]="ログアウトしました。"
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #ログインしているユーザーでなければurlを打ち込んでもlogin_pathに飛ばす
  skip_before_action :login_required,{except: [:edit, :show, :update]}

  #ログインユーザーでなければ編集できない
  before_action :ensure_correct_user,{only: [:show, :edit, :update]}
  before_action :set_user,{only: [:show, :edit, :edit, :update]}

  def index
    @users=User.all.page(params[:page]).per(10)
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)

    if @user.save
      flash[:notice]="登録に成功しました。"
      redirect_to login_path
    else
      flash.now[:alert]="登録に失敗しました。"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice]="更新に成功しました。"
      redirect_to user_path
    else
      flash.now[:alert]="更新に失敗しました。"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def set_user
    @user=User.find(params[:id])
  end

  #ログイン中のユーザしか編集できない処理
  def ensure_correct_user
    if current_user.id !=  params[:id].to_i
     flash[:alert]="権限をお確かめください。"
     redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/imagesposts_helper.rb
module ImagespostsHelper
end

app/helpers/imgposts_helper.rb
module ImgpostsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/homes/index.html.erb
<% provide(:title, "ホーム") %>
<div class="homes_top">
  <div class="container">
    <h1 class="homes_top_text">宇宙掲示板へようこそ</h1>

    <div class="posted_function_about">
      <h2>宇宙掲示板とは?</h2>
      <p>宇宙掲示板とはその名の通り、背景が宇宙であり普通の掲示板よりリッチな掲示板となっています。</p>
      <p>各画面で背景画像が違っている所も見所です。掲示板ではお好きなことを投稿できるフリーな掲示板となっています。</p>
    </div>

    <div class="how_to_use">
      <h2>使い方</h2>
      <p>1 初めての方は、新規登録画面より新規登録を行ってください。</p>
      <p>2 新規登録後は、ログイン画面よりメールアドレス、パスワードを使ってログインしてください。</p>
      <p>3 ログイン後は掲示板でお好きなことを投稿できます。(他人の投稿は、編集、削除ができません。)</p>
      <p>4 ログアウトボタンを押すとこのホーム画面に戻ります。</p>
    </div>

    <div class="new_function">
      <h2>新機能開発について</h2>
      <p>宇宙掲示板は、現在掲示板機能しかありませんが、今後新機能を追加する予定です。</p>
      <p>そこでこんな機能があったら便利とかこんな機能が欲しい思う方は遠慮なく掲示板に書き込んでください。</p>
      <p>皆様からのアイデアお待ちしております。</p>
    </div>
  </div>
</div>

app/views/imgposts/index.html.erb
<div class="imgpost_index_image">
  <div class="container">
    <h1>写真一覧</h1>
    <p>お気に入りの写真や面白い画像を投稿してください!(宇宙や宇宙人の写真など)</p>
    <p><%= link_to '投稿', new_imgpost_path, class: 'btn btn-primary' %></p>
  　<div class="row">
      <% @imgposts.each do |imgpost| %>
        <div class="col-md-4">
          <p>画像名:<%= imgpost.name %></p>
          <p>投稿者:<%= imgpost.user.name %></p>
          <p><%= image_tag imgpost.img.url ,class: 'imgpost_image'%></p>
          <p><%= link_to '削除', imgpost_path(imgpost), method: :delete, data: { confirm: "#{imgpost.name}を削除します。よろしいですか?"}, class: "btn btn-danger"%></p>
        </div>
      <% end %>
    </div>
    <div class="imgposts_paginate"><%= paginate @imgposts %></div>
  </div>
</div>

app/views/imgposts/new.html.erb
<div class="imgpost_new_image">
  <div class="container">
    <h1>写真投稿</h1>
    <%= form_with model:@imgpost, local: true do |f| %>
    <div class="form-group">
      <span><i class="fas fa-file-signature"></i> <%= f.label :name %>(10文字以内)</span>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
      <div class="form-group">
        <span><i class="fas fa-image"></i> <%= f.label :img %></span>
        <%= f.file_field :img, class: 'form-control' %>
      </div>
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash.notice.present? %>
  <div class="alert alert-success">
    <%= flash.notice %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>
    <!-- googleAdsence -->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
         (adsbygoogle = window.adsbygoogle || []).push({
              google_ad_client: "ca-pub-8631639747990656",
              enable_page_level_ads: true
         });
    </script>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <% if current_user %>
      <%= link_to '掲示板', posts_path, class: 'navbar-brand' %>
    <% else %>
      <%= link_to 'ホーム', root_path, class: 'navbar-brand' %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <%= link_to '新規投稿', new_post_path, class: 'nav-link' %>
        <%= link_to '写真一覧', imgposts_path, class: 'nav-link' %>
        <%= link_to 'ユーザー詳細', user_path(current_user), class: 'nav-link' %>
        <%= link_to 'ユーザー編集', edit_user_path(current_user), class: 'nav-link' %>
        <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to '新規登録', new_user_path, class: 'nav-link' %>
        <%= link_to 'ログイン', login_path, class: 'nav-link' %>
      <% end %>
      <%= link_to '戻る', :back, class: 'nav-link' %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    </form>
  </div>
</nav>


  <% if flash.notice.present? %>
    <div class="alert alert-success">
      <%= flash.notice %>
    </div>
  <% end %>

  <% if flash.alert.present? %>
    <div class="alert alert-danger">
      <%= flash.alert %>
    </div>
  <% end %>


  <%= yield %>

  <footer>
    <p>&copy; 2019 T-Yuma</p>
  </footer>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
<div class=form-group>
  <span><i class="fas fa-edit"></i> <%= f.label :content %></span>
  <%= f.text_field :content, class: 'form-control' %>
</div>
<%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "投稿編集") %>
<div class="post_edit">
  <div class="container">
    <h1>編集</h1>

    <%= render partial: 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "宇宙掲示板") %>
<div class="posted_function_image">
  <h1 class="posted_function_title">宇宙掲示板</h1>
  <div class="posted_function">
    <% @posts.each do |post| %>
    <div class="posted_user_info">
      <%= link_to post.id, post %>:&ensp;&ensp;ユーザー&ensp;:&ensp;<%= post.user.name %>&ensp;&ensp;<%= post.created_at %>&ensp;&ensp;
    </div>
    <div class="post_content">
      &ensp;&ensp;&ensp;&ensp;&nbsp;
      <%= post.content %>
    </div>
    <% end %>
  </div>
  <div class="paginate"><%= paginate @posts %></div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>
<div class="post_edit">
  <div class="container">
    <h1>新規投稿</h1>

    <%= render partial: 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "投稿編集") %>
<div class="post_show_image">
  <div class="container">
    <h1>投稿詳細</h1>
    <table class="table table-hover">
      <tbody>
        <tr>
          <th class="post_show_text"><%= Post.human_attribute_name(:id) %></th>
          <td class=post_show_text><%= @post.id %></td>
        </tr>
        <tr>
          <th class="post_show_text"><%= Post.human_attribute_name(:content) %></th>
          <td class="post_show_text"><%= @post.content %></td>
        </tr>
      </tbody>
    </table>
    <p>
      <%= link_to '編集', edit_post_path, class: 'btn btn-primary' %>&nbsp
      <%= link_to '削除', post_path, method: :delete, data: { confirm: 'この投稿を削除します。よろしいですか?'}, class: 'btn btn-danger' %>
    </p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.present? %>
  <div id="errors">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
<div class="form-group">
  <span><i class="fas fa-user"></i> <%= f.label :name %></span>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <span><i class="fas fa-envelope"></i> <%= f.label :email %></span>
  <%= f.text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <span><i class="fas fa-lock"></i> <%= f.label :password %></span>
  <%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
  <span><i class="fas fa-lock"></i> <%= f.label :password_confirmation %></span>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>
<%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>
<div class="user_edit_image">
  <div class="container">
    <h1>ユーザー編集</h1>
    <!--エラーメッセージ-->
    <%= render "shared/error_messages", obj: @user %>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<div class="user_image">
  <div class="container">
    <h1>新規登録</h1>
    <!--エラーメッセージ-->
    <%= render "shared/error_messages", obj: @user %>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "ユーザー詳細") %>
<div class="user_show_image">
  <div class="container">
    <h1>ユーザー詳細</h1>
    <table class="table table-hover">
      <tbody>
        <tr>
          <th class="user_show_th"><%= User.human_attribute_name(:id) %></th>
          <td class="user_show_td"><%= @user.id %></td>
        </tr>
        <tr>
          <th class="user_show_th"><%= User.human_attribute_name(:name) %></th>
          <td class="user_show_td"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="user_show_th"><%= User.human_attribute_name(:email) %></th>
          <td class="user_show_td"><%= @user.email %></td>
        </tr>
        <tr>
          <th class="user_show_th"><%= User.human_attribute_name(:created_at) %></th>
          <td class="user_show_td"><%= @user.created_at %></td>
        </tr>
        <tr>
          <th class="user_show_th"><%= User.human_attribute_name(:updated_at) %></th>
          <td class="user_show_td"><%= @user.updated_at %></td>
        </tr>
      </tbody>
    </table>

    <%= link_to 'ユーザー編集', edit_user_path, class: 'btn btn-primary user_edit_link' %>
  </div>
</div>